wisdom/tess/urls.py
from django.urls import path
from . import views
app_name = 'tessurl'

urlpatterns = [
    path('', views.hello, name = 'index'),
    path('mission/', views.work, name = 'mission'),
    path('getinvolved/', views.join, name = 'getinvolved'),
    path('gallery/', views.myblog, name = 'gallery'),
    path('donate/', views.don, name = 'donate'),
    path('home/', views.myhome, name = 'home'),
    path('media/', views.mymedia, name = 'media'),
]

wisdom/wisdom/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tess.urls', namespace='index'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

wisdom/tess/models.py
from django.db import models

# Create your models here.
from django.utils.text import slugify


class prove(models.Model):
    name = models.CharField(max_length=200, null=False, blank=False)
    email = models.CharField(max_length=200, null=False, blank=False)
    occupation = models.CharField(max_length=200, null=False, blank=False)
    address = models.CharField(max_length=200, null=False, blank=False)
    state = models.CharField(max_length=200, null=False, blank=False)
    country = models.CharField(max_length=200, null=False, blank=False)
    option = models.CharField(max_length=200, null=False, blank=False)
    sub = models.FileField()

    def __str__(self):
        return self.name

class grate(models.Model):
    caption = models.CharField(max_length=200)
    image = models.FileField(upload_to="img/%y")
    def __str__(self):
        return self.caption

class hmm(models.Model):
    caption = models.CharField(max_length=200)
    link = models.CharField(max_length=200)
    hes = models.CharField(max_length=200)
    main_news = models.CharField(max_length=400)
    def __str__(self):
        return self.caption

wisdom/tess/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import prove
from .models import grate
from .models import hmm
# Create your views here.

def hello(request):
    return render(request, 'index.html')

def work(request):
    return render(request, 'mission.html')

def join(request):
    return render(request, 'involve.html')

def don(request):
    if request.method == 'POST':
        full_name = request.POST['name']
        email = request.POST['email']
        occupation = request.POST['occupation']
        address = request.POST['address']
        state = request.POST['state']
        country = request.POST['country']
        opt = request.POST['optional']
        prof = request.POST['proof']

        data = prove(name=full_name, email=email, occupation=occupation, address=address, state=state, country=country, option=opt, sub=prof)
        data.save()
    
    wis = grate.objects.all()
    return render(request, 'donate.html', {"wis":wis})


def myhome(request):
    return render(request, 'home.html')

def myblog(request):
    
    return render(request, 'blog.html')

def mymedia(request):
    fam = hmm.objects.all()
    return render(request, 'media.html', {"fam":fam})

# def love(request):
    

wisdom/tess/templates/donate.html
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="../static/milogo.png" type="image/x-icon">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.js'%}">
    
    
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
    <title>Miracle Foundation International</title>
        
  </head>
   <!-- background video -->
   <div class="navigate">
    <nav class="navbar navbar-expand-lg  navbar-light bg-dark text-dark">
      <a class="navbar-brand" href="#"> <img src="{% static './img/miracle_fdn_logo.png'%}" alt=""></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto list">
          <li class="nav-item active">
            <a class="nav-link internal" href="{% url 'tessurl:home' %}">HOME <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item active">
            <a class="nav-link internal" href="{% url 'tessurl:gallery' %}">GALLERY<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item active">
            <a class="nav-link internal" href="{% url 'tessurl:getinvolved' %}">GET INVOLVED <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item active">
            <a class="nav-link internal" href="{% url 'tessurl:media' %}">MEDIA <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item active">
            <a class="nav-link internal" href="{% url 'tessurl:mission' %}"> OUR MISSION <span class="sr-only">(current)</span></a>
          </li>
        </li>
        <li class="nav-item active">
          <a class="nav-link internal" href="{% url 'tessurl:donate' %}"> DONATE <span class="sr-only">(current)</span></a>
        </li>
        <!-- <button type="button" class="donor"><a href="#">DONATE</a></button> -->
      </ul>
          
         
      </div>
    </nav>
  </div>
  <!-- DONATE -->
<!-- DONATE -->
  
     
<div class="container">
  <div class="title">Please make a donation to any of our crypto wallet below and fill out the form <br>
     <b> Anonymous, do not fill the form</b></div>
  <div class="row fill">
    {% for w in wis %}
    <div class="col">
      <img src="{{w.image.url}}" alt="" style="width: 20rem;">
      <p class="wallet"> <b>{{w.caption}}</b></p>
    </div>
    {% endfor %}
    
    
  </div>
            <form action="#" method="POST"> {% csrf_token %}
        <div class="user-details">
          <div class="input-box">
            <span class="details"> Full Name </span>
            <input type="text" placeholder="Enter your full name" name="name" required>
          </div>
          <div class="input-box">
            <span class="details"> Email </span>
            <input type="email" placeholder="Enter your email address" name="email" required>
          </div>
          <div class="input-box">
            <span class="details"> Occupation </span>
            <input type="text" placeholder=" Enter your occupation " name="occupation" >
          </div>
          <div class="input-box">
            <span class="details"> Address </span>
            <input type="text" id="address" placeholder=" Enter your address " name="address" required>
          </div>
          <div class="input-box">
            <span class="details"> State/Province </span>
            <input type="text" id="state" placeholder="Enter your state/province" name="state" required>
          </div>
          <div class="input-box">
            <span class="details"> Country </span>
            <input type="text" id="country" placeholder="Enter your country" name="country" required>
          </div>
          <div class="input-box">
            <span class="details"> How did you know about us? </span>
            <input type="text" placeholder="Optional" name="optional" >
          </div>
          
          <div class="input-box">
            <span class="details"> Comment?</span>
            <input type="text" placeholder="Please leave a comment..." name="proof" required>
          </div>

          <button type="submit" id="submit" class="btn btn-primary">Submit</button>
        </div>
        
      </form>
      <div class="title">Your 1$ means a lot to us as we strived on making this foundation provide the basic needs that these orphans need and to make them have the ultimate love and care a normal child should have. <br>Thank you for joining the Miracle Foundation family. Your donation will have on-the-ground impact. For monthly donations, your gifts will help even more children. Here are a few examples to help you picture your generosity in action.
       <br> $50 provides nutritious food to 3 children each month.
        
        <br>$100 provides a month of support for a child waiting to go home.
        
       <br> $150 provide a tablet + a year of wifi to a new child each month.
        
       <br> $250 provides resources to support a family when a child returns home. <br> WE ARE VERY GRATEFUL FOR YOUR SUPPORT!!!<br>
        <b></b></div>
      
    </div>

  

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script>

  $("#submit").click(function(){
    swal({
          title: "Successful!",
          text: "A mail have been sent to your email",
          icon: "success",
          button: "ok",
        });
  });
  
</script>


    {% include 'footer.html' %}

    

wisdom/tess/templates/footer.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.js'%}">
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
    <title>Document</title>
        
</head>
<marquee behavior="" direction="" class="fut"> <b>The foundation is very grateful of your generousity towards securing the future of the children!!!</b>  </marquee>

<div class="footer">
    <h1> A family for every child in our lifetime</h1>
    <a href="{% url 'tessurl:donate' %}" class="btn btn-primary"> DONATE TODAY </a>
  </div>
  <div class="summary">
    <div class="row summ" style="width: 100%;">
      <div class="col">
       <img src="{% static './img/miracle_fdn_logo.png'%}" alt="">
       <form class="talk">
         <p><i>Talk to Miracle Foundation</i></p>
         <input type="email" name="" id="" placeholder="your email">
         <input type="text" name="" id="" placeholder="Talk to us">
         <a href=""><button id="submit"> Submit </button></a>
       </form>
      </div>
      <div class="col contact">
        <a href="{% url 'tessurl:mission' %}">About us | </a> <a href="{% url 'tessurl:mission' %}"> Our Mission | </a> <a href="http://wa.me/2348119110220">Contact Us on Social Media | </a> <a href="{% url 'tessurl:gallery' %}">Our Gallery | </a> <a href="{% url 'tessurl:media' %}"> Press Coverage | </a> <a href="{% url 'tessurl:getinvolved' %}"> Partners </a>
        <a href="{% url 'tessurl:getinvolved' %}">Our teams | </a> <a href="{% url 'tessurl:donate' %}"> Give a gift | </a> <a href="{% url 'tessurl:donate' %}"> Fund raise | </a> <a href=""> How we measure our success | </a>
        <a href=""> Matching gifts</a>

        <!-- <div class="modal-container" id="modal-container">
          <div class="modal" id="modal">
            <button class="close-btn" id="close"></button>
            <div class="modal-content">
              <div class="header">
                <h2 class="logo"> Suscribe to Our Newsletter</h2>
                <p class="tagline"> Join the Mission</p>
                <p>Enter Your Email Address Below</p>
              </div>
              <form>
                <input type="text" placeholder="enter your email">
                <button class="subscribe">Subscribe</button>
              </form>
            </div>
          </div>
        </div> -->
        

      </div>
    </div>
    <div class="reserved">
      <p>© 2022 Miracle Foundation. All rights reserved. | website: Sterling Marketing Group and David Kerr Design</p>
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <script src="script.js"></script>
  <script>
    $(document).ready(function(){

      function showModal(){
        $('#modal-container').show();
        // $('html body').css('overflow', 'hidden');
      }

      function closeModal(){
        $('#modal-container').hide();
      }

      setTimeout(showModal,3000);

      $('#close').click(function(){
        closeModal();
        
      })
    });
  </script>
  </html>

wisdom/tess/templates/header.html
{% load static %}
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="shortcut icon" href="../static/milogo.png" type="image/x-icon">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.js'%}">
  <link rel="stylesheet" href="{% static 'css/style.css'%}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  <!-- <script>

  </script> -->
  
  <title>Miracle Foundation International</title>
      
</head>
 <!-- background video -->
 <div class="navigate">
  <nav class="navbar navbar-expand-lg  navbar-light bg-dark text-dark">
    <a class="navbar-brand" href="#"> <img src="{% static './img/miracle_fdn_logo.png'%}" alt=""></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto list">
        <li class="nav-item active">
          <a class="nav-link internal" href="{% url 'tessurl:home' %}">HOME <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link internal" href="{% url 'tessurl:gallery' %}">GALLERY<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link internal" href="{% url 'tessurl:getinvolved' %}">GET INVOLVED <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link internal" href="{% url 'tessurl:media' %}">MEDIA <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link internal" href="{% url 'tessurl:mission' %}"> OUR MISSION <span class="sr-only">(current)</span></a>
        </li>
      </li>
      <li class="nav-item active">
        <a class="nav-link internal" href="{% url 'tessurl:donate' %}"> DONATE <span class="sr-only">(current)</span></a>
      </li>
      <!-- <button type="button" class="donor"><a href="#">DONATE</a></button> -->
    </ul>
        
       
    </div>
  </nav>
</div>
<div class="section">
  
  <video autoplay loop muted style="width: 100%;">
    <source src="{% static './media.io_Home-Page-Banner_v2small.mp4'%}">
    
  </video>
  <h3 class="potential"> EMPOWERING ORPHANS AND <br> VUNERABLE CHILDREN <br> to reach their <br> full potential </h3>
  <button type="button" class="work"><a href="{% url 'tessurl:mission' %}">OUR WORK</a></button>
  </div>

wisdom/tess/templates/home.html
{% include 'index.html' %}

wisdom/tess/templates/index.html
{% include 'header.html' %}
{% load static %}
{% block content %}


      <!-- Second phase -->
      <div class="analysis">
        <center>
        <div class="row live" style="width: 100%;">
          <div class="col">
            <center><img src="{% static './help1.svg'%}" style="width: 20%;" alt=""></center>
            <p>Children's live improved</p>
          </div>
          <div class="col">
            <center><img src="{% static './help1.svg'%}" style="width: 20%;" alt=""></center>
           <p>Government workers and childcare providers trained</p>
          </div>
          <div class="col">
            <center><img src="{% static './help1.svg'%}" style="width: 20%;" alt=""></center>
            <p>Children reunited with families</p>
          </div>
        </div>
        </center>
        
      </div>
      <!-- Core Initiative -->
      <div class="core">
        <center><h3>OUR CORE  INITIATIVES</h3></center>
        <center>
        <div class="row" style="width: 100%;">
          <div class="col share">
            <div class="card text-white share">
              <img src="../static/images (3).jpeg" class="card-img" alt="...">
              <div class="image">
                
                <p class="foster">Connect the US Foster Care System <br>  Reports, services, agencies, regulations. The US Foster Care System can be frustrating to manage for foster families. But our new FosterShare™ app is changing all that.</p>
                
                <button type="button" class="don"><a href="{% url 'tessurl:donate' %}"> DONATE </a> </button>
              </div>
              
            </div>
          </div>
          <div class="col share">
            <div class="card  text-white share">
              <img src="{% static '../static/images (6).jpeg'%}" class="card-img" alt="...">
              <div class="image">
                
                <p class="foster">Prevent Children from Entering the System <br>The orphan crisis will never end until we stop it at the source. This means: Identifying vulnerable families long before the idea of child placement is necessary. Here’s how we do it.</p>
                <button type="button" class="don"><a href="{% url 'tessurl:donate' %}"> DONATE </a> </button>
              </div>
             
            </div>
            
          </div>
          <div class="col share">
            <div class="card text-white share">
              <img src="{% static '../static/images (1).jpeg'%}" class="card-img" alt="...">
              <div class="image">
                
                <p class="foster">Transition Children from Orphanages to Families <br> It’s time to move from orphanages to families, and we have a proven field-tested method to make sure this is done safely. Help us bring them home.</p>
                
                <button type="button" class="don"><a href="{% url 'tessurl:donate' %}"> DONATE </a> </button>
              </div>
              
            </div>
          </div>
        </div>
      </center>
      </div>
      <!-- how we measure success -->
      <div class="row thrive" style="width: 100%;">
        <div class="col">
          <img src="{% static './Thrive-Scale-anim-3.gif'%}" alt="" style="width: 100%;" >
        </div>
        <div class="col">
          <button class="measure"> OUR SUCCESS</button>
        </div>
      </div>
      <!-- next section -->
      <div class="next">
        <center><p>Miracle Foundation is part of a global network of non-profit organizations leading the worldwide movement to end the need for orphanages in our lifetime.</p></center>
      </div>
      <!-- media coverage -->
      <div class="media" style="width: 100%;">
        <center>
        <div class="row" style="width: 100%;">
          <div class="col" style="width: 100%;">
            <img src="{% static './media coverage.png'%}" alt="" style="width: 100%;">
          </div>
          <div class="col">
            <img src="{% static './unicef.png'%}" alt="">
          </div>
          <div class="col" style="width: 100%;">
            <img src="{% static './people.png'%}" alt="" style="width: 100%;" >
          </div>
        </div>
        <a href="{% url 'tessurl:media' %}">
        <button>Media Coverage</button>
      </a>
      </center>
      </div>
      <!-- picture -->
      <div>
        <img src="{% static './la.jpg'%}" alt="" style="width: 100%;">
      </div>
      <!-- Assiist us -->
      <div class="assist">
        <center>
        <div class="row" style="width: 100%;">
          <div class="col lest">
            <center>
            <div class="card">
               <div class="card-body">
                <p class="card-text">Your one time donation will help a child to thrive. Don't hesitate to donate, it is of utmost importance to us, helping us reunite the children with their families. Help Now</p>
                <a href="{% url 'tessurl:donate' %}" class="btn btn-primary now">Help Now</a>
              </div>
            </div>
          </center>

          </div>
          <div class="col lest">
            <center>
            <div class="card">
              <div class="card-body">
              
               <p class="card-text">There is no more powerful way to support the children we serve than by becoming a monthly contributor. Your charitable giving month after month keeps us.</p>
               <a href="{% url 'tessurl:donate' %}" class="btn btn-primary">Support Our Work </a>
             </div>
           </div>
          </center>

          </div>
          <div class="col lest">
            <center>
            <div class="card">
              <div class="card-body">
               
               <p class="card-text">It takes a village to raise a child. The inspiring individuals who join commit to support orphaned and vulnerable Indian children over a five-year-period..</p>
               <a href="{% url 'tessurl:donate' %}" class="btn btn-primary">Join The Village Today</a>
             </div>
           </div>
          </center>

          </div>
          <div class="col lest">
            <center>
            <div class="card">
              <div class="card-body">
               
               <p class="card-text">Legacy Partners commit to three years of high-level giving. They are changemakers, ending the orphan crisis by providing safe and loving homes for Children.</p>
               <a href="{% url 'tessurl:donate' %}" class="btn btn-primary">Make a Difference</a>
             </div>
           </div>
          </center>
          </div>
        </div>
      </center>
      </div>
      <!-- about us -->
      <div class="about">
        <h3> ABOUT </h3>
      <p> We know the very best thing for a child is to be part of a loving family—it’s where they thrive. That’s why everything we do as a children’s charity is designed to accomplish just that.

        Our goal is to replace orphanages with families for every child dreaming of home. We believe that together, we can change the way we care for children and help to get them into stable, loving, nurturing environments.
        
        Thanks to you, we are currently seeing our methodology used in more than 300 orphanages in India and are helping more than 15,000 vulnerable children and orphans to thrive.
        
        We believe in partnerships, and with generous gifts from people like you, we can make their dream of living with a family a reality.
      </p>
</div>

<!-- modal -->
<div class="bg-modal" id="modal-container">
  <div class="modal-content">
    <div class="close" id="close">+</div>
    <div class="modal-title">
      <h6>Suscribe To Receive Updates </h6>
      <p>Join our mailing list to receive the latest news and updates from our team.</p>
    </div>
    <div class="form">
      <input type="text" placeholder="Enter Your Full Names"> 
      <input type="email" placeholder="Enter Your E-Mail">
      <button type="submit"> Join The Movement</button>
    </div>
  </div>
</div>


      <!-- footer -->
      {% include 'footer.html' %}
    
</body>

{% endblock content %}

</html>

wisdom/tess/templates/involve.html
{% load static %}
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="shortcut icon" href="../static/milogo.png" type="image/x-icon">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.js'%}">
  <link rel="stylesheet" href="{% static 'css/style.css'%}">
  <title>Miracle Foundation International</title>
      
</head>
 <!-- background video -->
 <div class="navigate">
  <nav class="navbar navbar-expand-lg  navbar-light bg-dark text-dark">
    <a class="navbar-brand" href="#"> <img src="{% static './img/miracle_fdn_logo.png'%}" alt=""></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto list">
        <li class="nav-item active">
          <a class="nav-link internal" href="{% url 'tessurl:home' %}">HOME <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link internal" href="{% url 'tessurl:gallery' %}">GALLERY<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link internal" href="#">GET INVOLVED <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link internal" href="{% url 'tessurl:media' %}">MEDIA <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link internal" href="{% url 'tessurl:mission' %}"> OUR MISSION <span class="sr-only">(current)</span></a>
        </li>
      </li>
      <li class="nav-item active">
        <a class="nav-link internal" href="{% url 'tessurl:donate' %}"> DONATE <span class="sr-only">(current)</span></a>
      </li>
      <!-- <button type="button" class="donor"><a href="#">DONATE</a></button> -->
    </ul>
        
       
    </div>
  </nav>
</div>
<!-- partners -->
<div class="patty">
  <p><i>“If you want to go fast, go alone. If you want to go far – go together.” </i></p>
  <p style="text-align: right;"> <b> Old African Proverb </b> </p>
</div>
<div class="collab">
  <p> <b>Collaboration is Key. </b> With a dream as big as ours, it takes a vast network of partners to bring it to life. For those who have helped and those yet to join the team, we welcome you all and give thanks for your commitment.</p>
</div>
<div class="mapat" style="width: 100%;">
  <h4>P a r t n e r s</h4>
  <img src="../static/pattyy.png" alt="" style="width: 100%;">
</div>

    


{% include 'footer.html' %}

wisdom/tess/templates/mission.html
{% load static %}
{% include 'header.html' %}
<!-- our missions -->

  
   
<div class="miss">
      <center><h2 style="margin-top: 55px;"> OUR MISSION </h2></center>
      <h3> THE PROBLEM</h3>
      <p class="mission">As you read this, millions of children are separated from their families, living in institutions or on the streets. Many survive with substandard care, unloved and at risk – all of them dreaming of a family. In the worst cases, the orphanage environment exposes children to devastating abuse and psychological trauma, creating adults who are 10x more likely to become sex workers and 50x more likely to be in prison.

        But, we are also in the midst of a profound paradigm shift. Efforts are being made to reform foster care systems, support families before separation occurs and reunite families where preventable separation has occurred. <br> We all know kids everywhere deserve better.
        
        The movement has begun and Miracle Foundation is on the front line.</p>
      
    </div>
  
  
    <div class="muss">
      <h3 class="mt-0 mb-1"> OUR SOLUTION</h3>
      <p class="mission">Our work in the past was grounded in helping orphans in need to have a better quality of life but has evolved to also ensure that every child has an opportunity to grow up in a family. We’ve learned that children who are separated from their families yearn to go back and feel the love and belonging a family can offer. <br> At Miracle Foundation, our vision is a family for every child in our lifetime.</p>
    </div>
    
  
{% include 'footer.html' %}